apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: Helm
{{- if .Values.storageClass.makeDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: ebs.csi.aws.com
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion | default true }}
parameters:
{{- range $key, $value := .Values.storageClass.parameters }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
reclaimPolicy: Delete
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode | default "WaitForFirstConsumer" }}
