name: "letsencrypt-dns01"

email: ""  
server: "https://acme-v02.api.letsencrypt.org/directory"  

privateKeySecretName: "acme-account-key"

region: "us-east-1"
hostedZoneID: ""

roleARN: ""

zones: []

nameOverride: ""
fullnameOverride: ""
